freq_table = [
    { freq = 265000, volt = 52500, ddr_opp = 999 },
    { freq = 349000, volt = 55000, ddr_opp = 999 },
    { freq = 439000, volt = 57500, ddr_opp = 999 },
    { freq = 531000, volt = 59375, ddr_opp = 999 },
    { freq = 642000, volt = 62500, ddr_opp = 999 },
    { freq = 731000, volt = 64375, ddr_opp = 3 },
    { freq = 820000, volt = 66875, ddr_opp = 0 },
    { freq = 910000, volt = 69375, ddr_opp = 0 },
    { freq = 1001000, volt = 71250, ddr_opp = 0 },
    { freq = 1047000, volt = 72500, ddr_opp = 0 }
]
